// TESTING PURPOSES

export const HANDLEDECREASE = 'HANDLEDECREASE';
export const HANDLEINCREASE = 'HANDLEINCREASE';
export const FETCH_DATA_FROM_SERVER = 'FETCH_DATA_FROM_SERVER';

// MONGO HANDLER

export const FETCH_DB = 'FETCH_DB';